### ISSUE TITLE
Erro ao incluir StudentTest.java (kill.csv not found)

### ISSUE THREAD

**Issue by margarida-assis** [PedroTav/defects4j#2]
Tenho o projeto Lang53 com a ferramenta Major, quando tento incluir os student test cases no Generate aparece-me este erro:

```bash
Traceback (most recent call last):

  File "/home/tvvs/Desktop/defects4j/analyzer/analyzer.py", line 137, in <module>

    main()

  File "/home/tvvs/Desktop/defects4j/analyzer/analyzer.py", line 131, in main

    project.run_tools(tools, **kwargs)

  File "/home/tvvs/Desktop/defects4j/analyzer/analyzer/project.py", line 379, in run_tools

    self._run_tool(tool, **kwargs)

  File "/home/tvvs/Desktop/defects4j/analyzer/analyzer/project.py", line 330, in _run_tool

    tool.get_output()

  File "/home/tvvs/Desktop/defects4j/analyzer/analyzer/tools.py", line 112, in get_output

    raise FileNotFoundError(msg)

FileNotFoundError: /home/tvvs/Lang-53f/kill.csv not found.

If you executed run() before, then the tool got an error.

Try re-executing with --stdout and --stderr to see logs.
```

Este é o meu ficheiro StudentTest.java:

```java
package org.apache.commons.lang.time;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.TimeZone;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;
import junit.textui.TestRunner;

/*
 * Unit tests {@link org.apache.commons.lang.time.DateUtils}.
 */
public class StudentTest extends TestCase {

    private static final long MILLIS_TEST;
    static {
        GregorianCalendar cal = new GregorianCalendar(2000, 6, 5, 4, 3, 2);
        cal.set(Calendar.MILLISECOND, 1);
        MILLIS_TEST = cal.getTime().getTime();
    }

    DateFormat dateParser = null;
    DateFormat dateTimeParser = null;
    DateFormat timeZoneDateParser = null;
    Date dateAmPm1 = null;
    Date dateAmPm2 = null;
    Date dateAmPm3 = null;
    Date dateAmPm4 = null;
    Date date0 = null;
    Date date1 = null;
    Date date2 = null;
    Date date3 = null;
    Date date4 = null;
    Date date5 = null;
    Date date6 = null;
    Date date7 = null;
    Date date8 = null;
    Calendar calAmPm1 = null;
    Calendar calAmPm2 = null;
    Calendar calAmPm3 = null;
    Calendar calAmPm4 = null;
    Calendar cal1 = null;
    Calendar cal2 = null;
    Calendar cal3 = null;
    Calendar cal4 = null;
    Calendar cal5 = null;
    Calendar cal6 = null;
    Calendar cal7 = null;
    Calendar cal8 = null;
    TimeZone zone = null;
    TimeZone defaultZone = null;

    public StudentTest(String name) {
        super(name);
    }

    public static void main(String[] args) {
        TestRunner.run(suite());
    }

    public static Test suite() {
        TestSuite suite = new TestSuite(StudentTest.class);
        suite.setName("StudentTest Tests");
        return suite;
    }

    protected void setUp() throws Exception {
        super.setUp();

        dateParser = new SimpleDateFormat("MMM dd, yyyy", Locale.ENGLISH);
        dateTimeParser = new SimpleDateFormat("MMM dd, yyyy H:mm:ss.SSS", Locale.ENGLISH);

        dateAmPm1 = dateTimeParser.parse("February 3, 2002 01:10:00.000");
        dateAmPm2 = dateTimeParser.parse("February 3, 2002 11:10:00.000");
        dateAmPm3 = dateTimeParser.parse("February 3, 2002 13:10:00.000");
        dateAmPm4 = dateTimeParser.parse("February 3, 2002 19:10:00.000");
        date0 = dateTimeParser.parse("February 3, 2002 12:34:56.789");
        date1 = dateTimeParser.parse("February 12, 2002 12:34:56.789");
        date2 = dateTimeParser.parse("November 18, 2001 1:23:11.321");
        defaultZone = TimeZone.getDefault();
        zone = TimeZone.getTimeZone("MET");
        TimeZone.setDefault(zone);
        dateTimeParser.setTimeZone(zone);
        date3 = dateTimeParser.parse("March 30, 2003 05:30:45.000");
        date4 = dateTimeParser.parse("March 30, 2003 01:10:00.000");
        date5 = dateTimeParser.parse("March 30, 2003 01:40:00.000");
        date6 = dateTimeParser.parse("March 30, 2003 02:10:00.000");
        date7 = dateTimeParser.parse("March 30, 2003 02:40:00.000");
        date8 = dateTimeParser.parse("October 26, 2003 05:30:45.000");
        dateTimeParser.setTimeZone(defaultZone);
        TimeZone.setDefault(defaultZone);
        calAmPm1 = Calendar.getInstance();
        calAmPm1.setTime(dateAmPm1);
        calAmPm2 = Calendar.getInstance();
        calAmPm2.setTime(dateAmPm2);
        calAmPm3 = Calendar.getInstance();
        calAmPm3.setTime(dateAmPm3);
        calAmPm4 = Calendar.getInstance();
        calAmPm4.setTime(dateAmPm4);
        cal1 = Calendar.getInstance();
        cal1.setTime(date1);
        cal2 = Calendar.getInstance();
        cal2.setTime(date2);
        TimeZone.setDefault(zone);
        cal3 = Calendar.getInstance();
        cal3.setTime(date3);
        cal4 = Calendar.getInstance();
        cal4.setTime(date4);
        cal5 = Calendar.getInstance();
        cal5.setTime(date5);
        cal6 = Calendar.getInstance();
        cal6.setTime(date6);
        cal7 = Calendar.getInstance();
        cal7.setTime(date7);
        cal8 = Calendar.getInstance();
        cal8.setTime(date8);
        TimeZone.setDefault(defaultZone);
    }

    protected void tearDown() throws Exception {
        super.tearDown();
    }
    
    public void testIsSameDay_Date() {
        Date date1 = new GregorianCalendar(2004, 6, 9, 13, 45).getTime();
        Date date2 = new GregorianCalendar(2004, 6, 9, 13, 45).getTime();
        assertEquals(true, DateUtils.isSameDay(null, date2));
        assertEquals(true, DateUtils.isSameDay(date1, null));   
    }
    
}
```

**Comment by jose** [comment]
@PedroTav, na test suite falta incluir

```java
import junit.framework.Assert.*;
```

De qualquer forma, o problema reportado continua...

**Comment by PedroTav** [comment]
Tentei verificar se a causa está do lado da GUI mas o problema permanece mesmo utilizado o terminal. Honestamente ainda não consegui perceber qual é a causa do ficheiro kill.csv não estar a ser gerado. Vou continuar a investigar.

```
2023-11-22 16:02:23,837 :: INFO :: [project.run_tools.340] :: Executing run_tools on tools [MajorTool]

2023-11-22 16:02:23,843 :: INFO :: [project.set_testsuite.186] :: StudentTest.java was inserted in current test suite

2023-11-22 16:02:23,859 :: INFO :: [project.set_testsuite.197] :: All dev tests copied into /home/pedrt/Lang-53f/src/test

2023-11-22 16:02:23,859 :: INFO :: [project.run_tools.349] :: Start run_tools for MajorTool

Running ant (compile)...................................................... OK

Running ant (compile.tests)................................................ OK

2023-11-22 16:02:27,293 :: INFO :: [project._run_tool.321] :: Setupping MajorTool...

2023-11-22 16:02:27,298 :: INFO :: [project._run_tool.323] :: Setup completed

2023-11-22 16:02:27,298 :: INFO :: [project._run_tool.325] :: Running MajorTool...

Compiling mutant definition (mml).......................................... OK

Running ant (mutate)....................................................... OK

Running ant (compile.tests)................................................ OK

Running ant (mutation.test)................................................ FAIL

Executed command:  cd /home/pedrt/Lang-53f && /home/pedrt/defects4j/major/bin/ant -f /home/pedrt/defects4j/framework/projects/defects4j.build.xml -Dd4j.home=/home/pedrt/defects4j -Dd4j.dir.projects=/home/pedrt/defects4j/framework/projects -Dbasedir=/home/pedrt/Lang-53f -Dbuild.compiler=major.ant.MajorCompiler -Dmajor.kill.log=/home/pedrt/Lang-53f/kill.csv  -logfile /home/pedrt/Lang-53f/.mutation.log   mutation.test 2>&1

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1G; support was removed in 8.0

Buildfile: /home/pedrt/defects4j/framework/projects/defects4j.build.xml

2023-11-22 16:02:40,872 :: INFO :: [project._run_tool.327] :: Execution completed

2023-11-22 16:02:40,872 :: INFO :: [project._run_tool.329] :: Collecting output...

Traceback (most recent call last):

  File "/home/pedrt/defects4j/analyzer/analyzer.py", line 137, in <module>

    main()

  File "/home/pedrt/defects4j/analyzer/analyzer.py", line 131, in main

    project.run_tools(tools, **kwargs)

  File "/home/pedrt/defects4j/analyzer/analyzer/project.py", line 379, in run_tools

    self._run_tool(tool, **kwargs)

  File "/home/pedrt/defects4j/analyzer/analyzer/project.py", line 330, in _run_tool

    tool.get_output()

  File "/home/pedrt/defects4j/analyzer/analyzer/tools.py", line 112, in get_output

    raise FileNotFoundError(msg)

FileNotFoundError: /home/pedrt/Lang-53f/kill.csv not found.

If you executed run() before, then the tool got an error.

Try re-executing with --stdout and --stderr to see logs.

```

**Comment by jose** [comment]
@margarida-assis @PedroTav, acho que descobri a razão do problema.  O teste `testIsSameDay_Date` falha quando executado.

```
java.lang.IllegalArgumentException: The date must not be null
	at org.apache.commons.lang.time.DateUtils.isSameDay(DateUtils.java:143)
	at org.apache.commons.lang.time.StudentTest.testIsSameDay_Date(StudentTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:520)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeInVM(JUnitTask.java:1484)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:872)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeOrQueue(JUnitTask.java:1972)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute1(JUnitTask.java:824)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:2277)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:392)
	at org.apache.tools.ant.Target.performTasks(Target.java:413)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:811)
	at org.apache.tools.ant.Main.startAnt(Main.java:217)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

Notem que a pré-condição de mutation testing é que todos os testes devem passar quando executados fora do contexto de mutation.  Espero que isto possa ajudar.

**Comment by jose** [comment]
@margarida-assis, esta issue está resolvida?  Por outras palavras, na sua máquina, se o seu conjunto de testes não tiver nenhum teste que falha, a ferramenta Major termina com sucesso?

**Comment by margarida-assis** [comment]
Sim, está resolvido. 
Consegui testar os casos que queria usando try catch.
Vou passar a correr `mvn test` sempre antes para me certificar que todos os testes passam.
Obrigada!

**Comment by jose** [comment]
> Vou passar a correr `mvn test` sempre antes para me certificar que todos os testes passam.

Sim, pode fazer isso.  Vou sugerir o uso `defects4j test`, simplesmente porque é o que está por baixo da GUI e provavelmente mais fiável que o `mvn test`.

**Comment by margarida-assis** [comment]
[like]  Margarida Assis Ferreira reacted to your message:
________________________________

**Comment by jose** [comment]
@PedroTav, acho que podemos fechar esta issue.
